export const constants = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOAD_USER: "LOAD_USER",
};

export const adminConstants = {
  GET_DASHBOARD: "GET_DASHBOARD",
  GET_TEACHERS: "GET_TEACHERS",
  GET_STUDENTS: "GET_STUDENTS",
  GET_ROLES: "GET_ROLES",
};
